require "glimmer-dsl-swt"
require "json"

require_relative "lib/sash_form_presenter"
require_relative "lib/main_window"
require_relative "lib/local_settings"
require_relative "lib/global_settings"
require_relative "lib/settings_window"
require_relative "lib/mapbar"
require_relative "lib/mapinfo_class"
require_relative "lib/map"
